# Super cell 
supercell: 
    file: traj-selection.xyz                                                    # Starting configuration
    format: extxyz
    index: 0

# FLARE calculator with (sparse) Gaussian process
flare_calc:
    gp: SGP_Wrapper
    file: otf_flare.json

# DFT Calculator --> Quantum Espresso
dft_calc:
    name: Espresso
    kwargs: 
        pseudopotentials: 
            H: H_ONCV_PBE-1.0.oncvpsp.upf
            N: N.oncvpsp.upf
            Fe: Fe.pbe-spn-kjpaw_psl.0.2.1.UPF 
            Co: Co_pbe_v1.2.uspp.F.UPF
        label: espresso
        tstress: True
        tprnfor: True
        nosym: True
        kpts: [2,2,1]
        koffset: [1,1,1]
        input_data: 
            control:
                prefix: espresso
                pseudo_dir: ./ 
                outdir: ./tmp
                calculation: scf
            system:
                ibrav: 0
                ecutwfc: 90
                ecutrho: 1080
                degauss: 0.04
                occupations: 'smearing'
                smearing: 'mv'
                nspin: 2
                starting_magnetization(1): 0.6
                starting_magnetization(2): 0.6
            electrons:
                conv_thr: 1.0e-6
                electron_maxstep: 200
                mixing_beta: 0.5
                mixing_mode: 'local-TF'
                startingwfc: 'file'
                startingpot: 'file'
    params: {}

# On-the-fly selection 
otf:  
    mode: fresh                                                                 
    md_engine: Fake                                                             # Do not perform MD, just read frames sequentially
    md_kwargs: 
        filenames: [ traj-selection.xyz ]
        format: extxyz
        index: ":"
        io_kwargs: {}
    initial_velocity: file                                                      # Initialize the velocities (units of Kelvin)
    dt: 0.001                                                                   # This value is arbitrary in this setting
    number_of_steps: 1000000                                                    # Total number of MD steps to be taken. Set to a value greater than the number of your DFT frames
    output_name: deal                                                           # output name
    init_atoms: [-1,-2]                                                         # init atoms from first frame to add to sparse set
    std_tolerance_factor: -0.1                                                  # The uncertainty threshold above which the DFT will be called. This value is typically scaled with the number of species (e.g., -0.05 for 2 species, -0.1 for 3, etc.)
    max_atoms_added: -1                                                         # Allow for all atoms in a given frame to be added to the sparse set if uncertainties permit              
    train_hyps: [10,20]                                                         # Define range in which hyperparameters will be optimized. Here, hyps are optimized at every DFT call after the 5th call.
    write_model: 1                                                              # Verbosity of model output.
    update_style: threshold                                                     # Sparse set update style. Atoms above a defined "threshold" will be added using this method
    update_threshold: 0.05                                                      # Threshold for adding atoms if "update_style = threshold". Threshold represents relative uncertainty to mean atomic uncertainty, where atoms above are added to sparse set. This value is typically set to be 0.1*std_tolerance_factor.
    force_only: False 