# DFT Calculator --> Quantum Espresso
dft_calc:
    name: Espresso
    kwargs: 
        pseudopotentials: 
            H: H_ONCV_PBE-1.0.oncvpsp.upf
            N: N.oncvpsp.upf
            Fe: Fe.pbe-spn-kjpaw_psl.0.2.1.UPF 
            Co: Co_pbe_v1.2.uspp.F.UPF
        label: espresso
        tstress: True
        tprnfor: True
        nosym: True
        kpts: [2,2,1]
        koffset: [1,1,1]
        input_data: 
            control:
                prefix: espresso
                pseudo_dir: ./ 
                outdir: ./tmp
                calculation: scf
            system:
                ibrav: 0
                ecutwfc: 90
                ecutrho: 1080
                degauss: 0.04
                occupations: 'smearing'
                smearing: 'mv'
                nspin: 2
                starting_magnetization(1): 0.6
                starting_magnetization(2): 0.6
            electrons:
                conv_thr: 1.0e-6
                electron_maxstep: 200
                mixing_beta: 0.5
                mixing_mode: 'local-TF'
                startingwfc: 'file'
                startingpot: 'file'
    params: {}