# FLARE calculator with (sparse) Gaussian process
flare_calc:
    gp: SGP_Wrapper
    kernels:
        - name: NormalizedDotProduct                                            # select kernel for comparison of atomic environments
          sigma: 2                                                              # signal variance, this hyperparameter will be trained, and is typically between 1 and 10.
          power: 2                                                              # power of the kernel, influences body-order
    descriptors:
        - name: B2                                                              # Atomic Cluster Expansion (ACE) descriptor from R. Drautz (2019). FLARE can only go from B1 up to B3 currently.
          nmax: 8                                                               # Radial fidelity of the descriptor (higher value = higher cost)
          lmax: 3                                                               # Angular fidelity of the descriptor (higher value = higher cost)
          cutoff_function: quadratic                                            # Cutoff behavior
          radial_basis: chebyshev                                               # Formalism for the radial basis functions
          cutoff_matrix: [[4,4,4,4],[4,4,4,4],[4,4,5.5,5.5],[4,4,5.5,5.5]]      # In angstroms. NxN array for N_species in a system. the order of the matrix corresponds to the list of chemical species (e.g., matrix element 1,1 is the cutoff for element 1 interacting with itself) 
    energy_noise: 0.1                                                           # Energy noise hyperparameter, will be trained later. Typically set to 1 meV * N_atoms.
    forces_noise: 0.05                                                          # Force noise hyperparameter, will be trained later. System dependent, typically between 0.05 meV/A and 0.2 meV/A.
    stress_noise: 0.001                                                         # Stress noise hyperparameter, will be trained later. Typically set to 0.001 meV/A^3.
    species:                                                                    # Atomic number of your species (here, 13 = Al). To add additional species, insert a new line below this one in the same format (e.g., - A#), where A# is the atomic number of the second species.
        - 1
        - 7                                                                     
        - 26
        - 27
    single_atom_energies:                                                       # Single atom energies to bias the energy prediction of the model. Can help in systems with poor initial energy estimations. Length must equal the number of species.
        - 0                                                                 
        - 0
        - 0
        - 0
    cutoff: 5.5
    variance_type: local                                                        # Calculate atomic uncertainties.
    max_iterations: 20                                                          # Maximum steps taken during each hyperparameter optimization call. Can sometimes be helpful to increase this value if hyperparameter optimization is unstable.
    use_mapping: True   