# On-the-fly training and MD with LAMMPS
otf: 
    mode: fresh
    md_engine: PyLAMMPS
    md_kwargs: 
        command: "lmp" # LAMMPS executable, e.g. srun /usr/bin/lammps/build/lmp
        specorder: [H, N, Fe, Co]
        masses: ["1 2.016000","2 14.007000","3 55.845000", "4 58.933194"]
        dump_period: 1
        pair_style: flare
        group: ["free id 5 6 7 8 9 10 15 16 17 18 19 20 25 26 27 28 29 30 35 36 37 38 39 40 45 46 47 48 49 50 55 56 57 58 59 60 65 66 67 68 69 70 75 76 77 78 79 80 85 86 87 88 89 90 95 96 97 98 99 100 105 106 107 108 109 110 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133", 
                "fixed id 1 2 3 4 11 12 13 14 21 22 23 24 31 32 33 34 41 42 43 44 51 52 53 54 61 62 63 64 71 72 73 74 81 82 83 84 91 92 93 94 101 102 103 104 111 112 113 114"] 
        fix: ["1 all plumed plumedfile plumed.dat outfile p.log ","2 free nve","3 free temp/csvr 700 700 0.1 1"]
        shell: ["[ ! -s KERNELS ] && cp plumed-fresh.dat plumed.dat || cp plumed-restart.dat plumed.dat"]
        keep_alive: False 
    initial_velocity: 700                                                       # Initialize the velocities (units of Kelvin)
    dt: 0.001                                                                   # Timestep
    number_of_steps: 10000                                                      # Total number of MD steps to be taken.
    output_name: otf                                                            # Output name
    init_atoms: [-1,-2]                                                         # init atoms from first frame to add to sparse set
    std_tolerance_factor: -0.1                                                  # The uncertainty threshold above which the DFT will be called. This value is typically scaled with the number of species (e.g., -0.05 for 2 species, -0.1 for 3, etc.)
    max_atoms_added: -1                                                         # Allow for all atoms in a given frame to be added to the sparse set if uncertainties permit              
    train_hyps: [10,inf]                                                        # Define range in which hyperparameters will be optimized. Here, hyps are optimized at every DFT call after the 5th call.
    write_model: 4                                                              # Verbosity of model output.
    update_style: threshold                                                     # Sparse set update style. Atoms above a defined "threshold" will be added using this method
    update_threshold: 0.01                                                      # Threshold for adding atoms if "update_style = threshold". Threshold represents relative uncertainty to mean atomic uncertainty, where atoms above are added to sparse set. This value is typically set to be 0.1*std_tolerance_factor.
    force_only: False                                                      
    dft_postprocessing: "srun pp.x -in ../../configs/qe/espresso.ppi > espresso.ppo" # Commands to postprocess DFT output
    store_dft_output: [[espresso.pwi, espresso.pwo, espresso.ppo, espresso.charge_density.cube], single-point/]
